# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg_app', '0003_auto_20170628_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poked_by', models.ManyToManyField(related_name='pokes', to='loginReg_app.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginReg_app.User')),
            ],
        ),
    ]
